### ISSUE TITLE
Video file without audio track does not play

### ISSUE THREAD

**Issue by davthedev** [kidrigger/godot-videodecoder#18]
Hi,

I discovered that some of the video files I wanted to play did not load. Those only have a video track.
To make sure if it is the cause, I took one of the working video files from the examples and stripped the audio track. I ran the following command:

ffmpeg -i echo-hereweare.mp4 -c copy -an echo-nosound.mkv

The resulting file does not load, although is plays correctly in other video players.
In addition, I see the following warnings in the console:

WARNING: godot_videodecoder_open_file(): Audio Stream not found.
   At: src/gdnative_videodecoder.c:437.

Running on Ubuntu 19.10

**Comment by kidrigger** [comment]
The warning is okay - the plugin prints it, but continues business as usual.
I need to check why it's not loading.

**Comment by jamie-pate** [comment]
Please try again with the latest changes
