### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by fire** [KidRigger/godot-videodecoder#2]
Are there instructions on how to build this?

**Comment by fire** [comment]
It seems to hard include binaries and I don't see any for Windows.

**Comment by fire** [comment]
The plugin is not able to build for godot master.

**Comment by fire** [comment]
Requires https://github.com/godotengine/godot/pull/20552

**Comment by fire** [comment]
env.Append(CPPPATH=['#thirdparty/include'])
env.Append(LIBPATH=['#thirdparty/lib'])

Had to add..

**Comment by KidRigger** [comment]
Binaries have to be built. The windows build on SCons was not made (Since I lacked access to a Windows system.) Now that I do, I'm working on Linux and Windows build versions.

I'll update the code to reflect the current Godot changes, this is lacking behind.

**Comment by KidRigger** [comment]
@fire README has been updated. Please test. Closing the issue now.

**Comment by KidRigger** [comment]
Works on Master directly now.
