### ISSUE TITLE
Upgrade to GDExtension for 4.0

### ISSUE THREAD

**Issue by fire** [kidrigger/godot-videodecoder#41]
GDNative was removed in Godot Engine 4.0.

**Comment by fire** [comment]
1. [ ] verify all things work
2. [ ] verify that audio sync issue is fixed
3. [ ] verify that the releases work as expected
4. [ ] investigate transfer to Godot Engine organization as an official plugin

**Comment by jamie-pate** [comment]
4 (transfer to godot org) would be really nice, I currently have very little time to help out with this :)

**Comment by zombietype** [comment]
I would prefer this being transferred to the org as well. It's an important part - and I lack the time to maintain this. Need to check if this can be easily moved to a GDExtension else it's better to be re-written as there are issues _due to mistaken core assumptions about the A/V playback_.

**Comment by fire** [comment]
Please document:

Mistaken core assumptions about the A/V playback.

**Comment by zombietype** [comment]
> Please document:
> 
> Mistaken core assumptions about the A/V playback.

Currently, the video plays as at the timestamp or earliest possible, with audio synchronizing to it.
This was to be fixed (but I'm unsure if it has been)
The correct way is for the video to synchronise to audio.

However this bug is on the godot side of the code. The decoder plugin itself shouldn't be affected and probably can just be copied over.

**Comment by aXu-AP** [comment]
Now that Godot 4 is nearing beta, is there any plans to continue working on this?

**Comment by zombietype** [comment]
The GDExtension repo is https://github.com/kidrigger/godot-video-reference

**Comment by aXu-AP** [comment]
Thanks! Is this going to support ffmpeg as well?

**Comment by zombietype** [comment]
That's the goal. Currently stuck due to lack of time on my part as I'm a
full time student.

Adding WebM support first since it was removed from Godot.
Then I'll make the ffmpeg one.

**Comment by aXu-AP** [comment]
Nice to hear and I wish you well on studys. I'd gladly help but C++ is no go for me :/

**Comment by Anemony22** [comment]
Is there any news on this? I'd love to use the seek functionality in a current project. Our current workaround is just linking to a YouTube video, which is less than ideal.

**Comment by yunylz** [comment]
bump?

**Comment by zombietype** [comment]
Those project should fit the needs.
This repo is not actively maintained.

https://github.com/EIRTeam/EIRTeam.FFmpeg
