### ISSUE TITLE
Opening the video files in the test project produces no result

### ISSUE THREAD

**Issue by sirus20x6** [kidrigger/godot-videodecoder#45]
I don't know if this project is still active, but when I open the project in godot and run it. I get the window with the open button. clicking on one of the 3 videos that comes up doesn't do anything. it just sits there. I assume it's supposed to be playing video. which versions of godot is this for?

**Comment by sirus20x6** [comment]
there are 4 erros listed
W 0:00:00.237   The function 'list_dir_begin()' returns a value, but this value is never used.
  <C++ Error>   RETURN_VALUE_DISCARDED
  <Source>      World.gd:13

W 0:00:00.237   The argument 'delta' is never used in the function '_process'. If this is intended, prefix it with an underscore: '_delta'
  <C++ Error>   UNUSED_ARGUMENT
  <Source>      World.gd:52

E 0:00:00.238   godot_videodecoder_open_file(): Format not recognized:  ()
  <C++ Source>  src/gdnative_videodecoder.c:549 @ godot_videodecoder_open_file()()
  <Stack Trace> World.gd:39 @ _open()
                World.gd:26 @ _ready()

E 0:00:01.811   godot_videodecoder_open_file(): Format not recognized:  ()
  <C++ Source>  src/gdnative_videodecoder.c:549 @ godot_videodecoder_open_file()()
  <Stack Trace> World.gd:39 @ _open()
                World.gd:31 @ _on_menubutton_index_pressed()

**Comment by zombietype** [comment]
The project is designed for Godot 3.0, tested upto Godot 3.1

It is inactive as GDNative support is removed in Godot 4.0
The new GDExtension version is in works.
